config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # トップページ
  root to: %(movies#index)

  resources :movies do
  	collection do
  		get :auto
  	end
  end

  # ポリシー
  namespace :policies do
    resources :terms, only: [:index]
    resources :privacy, only: [:index]
  end

  # エラー
  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/movie.rb
require "net/https"

class Movie
  include Mongoid::Document

  field :title, type: String
  field :movie_id, type: String
  field :user_count, type: Integer
  field :url, type: String
  field :image, type: String
  field :created_at, type: Time
  field :provide_name, type: String
  field :user_name, type: String
  field :profile_image_url, type: String
  field :provide_id, type: String
  field :body, type: String

  index({movie_id: 1}, {unique: true, name: "movie_index"})

  # YOUTUBE動画IDを取得
  def self.get_movie_id(feed)
    feed.urls.each do |url|
      location = url.expanded_url.to_s
      case location
      when /youtube\.com\/watch\?v=/
        movie_id = location.gsub(/^.*v=([A-Za-z0-9_-]+).*/, '\1')[0..10]
      when /youtu\.be/
        movie_id = location.gsub(/^.*youtu\.be\/([A-Za-z0-9_-]+).*/, '\1')[0..10]
      else
        # 何もしない
      end
      if movie_id.present?
        Movie.create_from_twitter(movie_id, feed)
      end
    end
  end

  def self.create_from_twitter(movie_id, feed)
    begin
      # API問い合わせ
      uri = URI.parse("https://www.googleapis.com/youtube/v3/videos?id=#{movie_id}&key=#{ENV['GOOGLE_API_KEY']}&fields=items(snippet(title,thumbnails))&part=snippet")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE
      req = Net::HTTP::Get.new(uri.request_uri)
      response = http.request(req)
      json = response.body
    rescue => e
      # ログの出力
      logger.error e
      logger.error e.backtrace.join("\n")
    else
      # データを保存
      created_at_day = Time.now.utc - 86400
      user_count = 1
      user_count += Movie.only(:id).desc(:created_at).where(movie_id: movie_id, :created_at.gt => created_at_day).count.to_i

      if hash = JSON.parse(json.force_encoding("UTF-8"))
        unless hash['items'].empty? && hash['items'][0].blank?
          movies = Movie.where(movie_id: movie_id, :created_at.gt => created_at_day, :user_count.gt => 0)
          movies.update_all(user_count: 0) if movies.present?
          old_movies = Movie.where(movie_id: movie_id, :created_at.lt => created_at_day)
          old_movies.destroy
          title = hash['items'][0]['snippet']['title'].presence || nil
          image = hash['items'][0]['snippet']['thumbnails']['medium']['url'].presence || nil
          @movie = Movie.new(user_count: user_count, movie_id: movie_id, title: title, image: image, url: "http://www.youtube.com/watch?v=#{movie_id}", created_at: feed.created_at.to_time, provide_name: feed.user.screen_name, user_name: feed.user.name, profile_image_url: feed.user.profile_image_url_https, provide_id: feed.id, body: feed.text)
          @movie.save
        end
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

	# エラー処理
  unless Rails.env.development?
	  rescue_from Exception, with: :render_500
	  rescue_from Mongoid::Errors::DocumentNotFound, with: :render_404
	  rescue_from ActionController::RoutingError, with: :render_404
	end

	# ルーティングエラー
	def routing_error
		raise ActionController::RoutingError.new(params[:not_found])
	end

	# NotFound
  def render_404(exception = nil)
    logger.error "Rendering 404 with exception: #{exception.message}" if exception
    logger.error exception.backtrace.join("\n") if exception
    respond_to do |format|
      format.html { render 'errors/error_404', status: 404 }
      # format.json { render json: { error: '404 error' }, status: 404 }
      # format.all { render nothing: true, status: 404 }
    end
  end

  # ErrorPage
  def render_500(exception = nil)
    logger.error "Rendering 500 with exception: #{exception.message}" if exception
    logger.error exception.backtrace.join("\n") if exception
    respond_to do |format|
      format.html { render 'errors/error_500', status: 500 }
      # format.json { render json: { error: '500 error' }, status: 500 }
      # format.all { render nothing: true, status: 500 }
    end
  end


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  # GET /contacts/new
	# お問い合わせ
	def new
		if params[:item_id]
			@item = Item.find(params[:item_id])
		end
		@contact = Contact.new
		respond_to do |format|
			format.html
		end
	end

	# POST /contacts
	# お問い合わせ登録
	def create
		@contact = Contact.new(contact_params)
		respond_to do |format|
			if params[:back]
				@contact.confirming = nil
				format.js {render 'admin/shared/form'}
				format.html {render :new}
			elsif @contact.save
				ContactMailer.create_notification_email(@contact).deliver_now
				ContactMailer.admin_create_notification_email(@contact).deliver_now
				format.js
			else
				format.js {render 'admin/shared/form'}
				format.html {render :new}
			end
		end
	end


	private

	def contact_params
		params.require(:contact).permit(:email, :name, :description, :confirming)
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	# GET /
	def index
		created_at_day = Time.now.utc - 86400
		@movies = Movie.order(user_count: :desc).order(created_at: :desc).where(:created_at.gt => created_at_day, :user_count.gt => 0).page(params[:page]).per(24)
		respond_to do |format|
			format.html
		end
	end

	# GET /movies/1
	def show
		@movie = Movie.find(params[:id])
		respond_to do |format|
			format.js
		end
	end

	# GET /auto
	def auto
		created_at_day = Time.now.utc - 86400
		@movies = Movie.order(user_count: :desc).order(created_at: :desc).where(:created_at.gt => created_at_day, :user_count.gt => 0).limit(100)
		respond_to do |format|
			format.js
		end
	end

end

app/controllers/policies/privacy_controller.rb
class Policies::PrivacyController < ApplicationController

  def index

  end
  
end

app/controllers/policies/terms_controller.rb
class Policies::TermsController < ApplicationController

  def index

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

	#メタタグの設定
	def default_meta_tags
		{
			site: "インターネットテレビくん - KANJIZAITV -",
			reverse: true,
			# title: "",
			description: "インターネットテレビくん - KANJIZAITV - は話題のYouTube動画をリアルタイムにランキングするウェブサービスです。今巷で話題のYouTube動画をいち早くチェックしよう。Twitterでは日刊ランキングを配信中！",
			keywords: "KANJIZAITV, インターネットテレビくん,インターネットテレビ, ミュージックビデオ, 動画, ランキング, 話題",
			canonical: "https://kanjizai.tv",
			og: {
				title: :title,
				url: "https://kanjizai.tv",
				image: image_url('logo.png'),
				site_name: "インターネットテレビくん - KANJIZAITV -",
				description: :description,
				locale: 'ja_JP'
			},
			twitter: {
				card: 'summary',
				site: '@kanjizaitv'
			}
		}
	end

	# キーワード取得
  def get_keywords(title)
    keywords = []
    keywords << %W(#{title} インターネットテレビくん KANJIZAITV Twitter 動画 YouTube)
  end
	
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

	#経過時間の表示
	def time_diff(time)
		diff = Time.now - time
		day_diff = (diff / 86400).to_i
		if day_diff >= 7
			if day_diff / 7 < 5
				return ((day_diff / 7).to_i).to_s + t("helpers.time_diff.weeks_ago")
			else
				return time.strftime("%-m月%-d日")
			end
		else
			if day_diff >= 1
				if day_diff == 1
					return t("helpers.time_diff.yesterday")
				else
					return ((day_diff).to_i).to_s + t("helpers.time_diff.days_ago")
				end
			else
				if diff >= 3600
					return ((diff / 3600).to_i).to_s + t("helpers.time_diff.hours_ago")
				elsif diff >= 120
					return ((diff / 60).to_i).to_s + t("helpers.time_diff.minuts_ago")
				else
					return t("helpers.time_diff.just_now")
				end
			end
		end
	end
	
end

app/helpers/policies/privacy_helper.rb
module Policies::PrivacyHelper
end

app/helpers/policies/terms_helper.rb
module Policies::TermsHelper
end

app/views/contacts/_create.html.haml
-# app/views/contacts/_create.html.haml
-# お問い合わせ送信

#contacts_create

	%p
		お問い合わせを受け付けました。
		%br<>
		担当者が確認の上、返答させていただきます。

app/views/contacts/create.js.erb
// app/views/contacts/create.js.erb
// お問い合わせ送信

$('#form').html('<%= j(render %(create)) %>')

app/views/contacts/new.html.haml
-# app/views/contacts/new.html.haml
-# お問い合わせ

.l-main-content
	.l-main-content__normal
		%article.p-contact
			%header.l-main-content__header
				%h1.l-main-content__header-title
					お問い合わせ
				%p.l-main-content__header-description
					当サービスへのお問い合わせは
					%br<>
					こちらからお願いします。
			
			#form
				= render %(form)

app/views/layouts/_analytics.html.haml
-# app/views/layouts/_analytics.html.haml
-# グーグルアクセス解析

:javascript
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	ga('create', 'UA-69031248-5', 'auto');

app/views/layouts/_meta_tags.html.haml
-# app/views/layouts/meta_tags.html.haml

%meta{charset: 'UTF-8'}
%meta{"http-equiv" => "X-UA-Compatible", content: "IE=edge"}
%meta{"http-equiv" => "content-language", content: "ja"}
%link{media: 'handheld', rel: 'alternate', href: request.original_url}
%meta{name: "viewport", content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"}
= favicon_link_tag '/favicon.ico'
= display_meta_tags default_meta_tags

app/views/layouts/application.html.haml
-# app/views/layouts/application.html.haml

!!!
%html{lang: 'ja'}
	%head
		-# タイトル
		= render 'layouts/meta_tags'
		= csrf_meta_tags

		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

		<!--[if lt IE 9]>
		= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "data-turbolinks-track" => true
		= javascript_include_tag "https://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js", "data-turbolinks-track" => true
		= javascript_include_tag "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js", "data-turbolinks-track" => true
		<![endif]-->

		-# Googleアクセス解析
		- if Rails.env.production?
			= render 'layouts/analytics'

	%body
		%header.header.headroom
			
			%h1
				= link_to image_tag(%(kanjizaitv.png), alt: %(インターネットテレビくん - KANJIZAITV - 話題のYouTube動画をリアルタイムにランキング)), root_path
			-#
				%nav
					%ul
						
						%li
							= link_to raw(%(#{fa_icon 'youtube-play'})), auto_movies_path, remote: true
						%li
							= link_to raw(%(#{fa_icon 'twitter'})), %(https://twitter.com/kanjizaitv), target: "_blank"
					
		.container
			= yield
		
		.auto_link
			= link_to raw(%(#{fa_icon 'play-circle'})), auto_movies_path, remote: true
		.twitter_link
			= link_to raw(%(#{fa_icon 'twitter'})), %(https://twitter.com/kanjizaitv), target: "_blank"

app/views/movies/_auto.html.haml
-# app/views/movies/_auto.html.haml
-# プレイヤー

#modal-overlay

	#modal-content
		%article
			.movie
				%iframe{src: %(https://www.youtube.com/embed/#{@movies.first.movie_id}?playlist=#{@movies.offset(1).pluck(:movie_id).join(',')}&enablejsapi=1&controls=1&color=white&disablekb=1&modestbranding=1&playsinline=1&rel=0&iv_load_policy=3&showinfo=1&autoplay=1)}

		%p.close-button#modal-close
			= fa_icon 'times'
			閉じる

app/views/movies/_movie.html.haml
-# app/views/movies/_movie.html.haml
-# 動画ボックス

- if params[:page].present?
	- rank = (params[:page].to_i - 1) * 24 + movie_counter + 1
- else
	- rank = movie_counter + 1

%article.movie
	.inner
		-# 画像
		.image
			= link_to image_tag(movie.image, alt: "YouTube動画：#{movie.title}"), movie_path(movie), remote: true
		-# タイトル
		%h3.title
			= %(#{rank}位)
			= link_to movie.title, movie_path(movie), remote: true
		-# ユーザー情報
		.user-profile
			= link_to image_tag(movie.profile_image_url, width: 30, alt: "Twiiterユーザー：#{movie.user_name}"), %(https://twitter.com/#{movie.provide_name}), target: %(blank)
			%ul
				%li
					= link_to movie.user_name, %(https://twitter.com/#{movie.provide_name}), target: %(blank)
				%li
					= link_to %(@#{movie.provide_name}), %(https://twitter.com/#{movie.provide_name}), target: %(blank)
			.twitter-follow
				= link_to raw(%(#{fa_icon 'twitter lg'})), %(https://twitter.com/#{movie.provide_name}/status/#{movie.provide_id}), target: %(blank)
		-# ツイート本文
		%p
			= auto_link movie.body, html: {target: %(blank)}
		-# コントロール
		%ul.twitter-controll
			%li
				= link_to raw(%(#{fa_icon 'reply'})), %(https://twitter.com/intent/tweet?in_reply_to=#{movie.provide_id}), target: %(blank)
			%li
				= link_to raw(%(#{fa_icon 'retweet'})), %(https://twitter.com/intent/retweet?tweet_id=#{movie.provide_id}), target: %(blank)
			%li
				= link_to raw(%(#{fa_icon 'star'})), %(https://twitter.com/intent/favorite?tweet_id=#{movie.provide_id}), target: %(blank)
			%li
				%time{datetime: movie.created_at.to_datetime}
					= link_to time_diff(movie.created_at.to_datetime), %(https://twitter.com/#{movie.provide_name}/status/#{movie.provide_id}), target: %(blank)

app/views/movies/_player.html.haml
-# app/views/movies/_player.html.haml
-# プレイヤー

%iframe{src: %(https://www.youtube.com/embed/#{@movie.movie_id}?enablejsapi=1&controls=1&color=white&disablekb=1&modestbranding=1&playsinline=1&rel=0&iv_load_policy=3&showinfo=1)}

app/views/movies/_show.html.haml
-# app/views/movies/_show.html.haml
-# 画像表示

#modal-overlay

	#modal-content
		%article
			.movie
				= render %(player)

		%p.close-button#modal-close
			= fa_icon 'times'
			閉じる

app/views/movies/auto.html.haml
-# app/views/movies/auto.html.haml
-# 動画自動再生詳細

- set_meta_tags site: %(インターネットテレビくん　KANJIZAITV), title: %(動画自動再生), description: %(動画自動再生ページ。)

%article.movies_show
	%h2
		動画自動再生
	%iframe{src: %(https://www.youtube.com/embed/#{@movies.first.movie_id}?playlist=#{@movies.offset(1).pluck(:movie_id).join(',')}&enablejsapi=1&controls=1&color=white&disablekb=1&modestbranding=1&playsinline=1&rel=0&iv_load_policy=3&showinfo=1&autoplay=1)}

app/views/movies/auto.js.erb
// app/views/movies/auto.js.erb
// 動画変更

// モーダルウィンドゥ
$('#modal-overlay').remove();
$('body').append("<%= j(render('auto')) %>");
openModalWindow();

app/views/movies/index.html.haml
-# app/views/movies/index.html.haml
-# 動画一覧


%section.movies
	.grid__col-sizer

	.grid__gutter-sizer
	= render @movies

.page-load-status
	.loader-ellips.infinite-scroll-request
		%span.loader-ellips__dot
		%span.loader-ellips__dot
		%span.loader-ellips__dot
		%span.loader-ellips__dot

= paginate @movies

app/views/movies/show.html.haml
-# app/views/movies/show.html.haml
-# 動画詳細

- set_meta_tags site: %(インターネットテレビくん　KANJIZAITV), title: @movie.title, description: %(#{@movie.title}の動画ページ。#{truncate(@movie.body, length: 120)}), keywords: get_keywords(@movie.title)

%article
	%h2
		= @movie.title
	%p
		= @movie.body
	= render %(player)

app/views/movies/show.js.erb
// app/views/movies/show.js.erb
// 動画変更

// モーダルウィンドゥ
$('#modal-overlay').remove();
$('body').append("<%= j(render('show')) %>");
openModalWindow();

app/views/policies/privacy/index.html.haml
-# app/views/policies/privacy/index.html.haml
-# プライバシー

- set_meta_tags site: %(amidaTV（アミダTV）), title: %(プライバシーポリシー), description: %(amidaTV（アミダTV）プライバシーポリシーページ。), canonical: request.original_url

%section.privacy
	%h2
		プライバシーポリシー
	%h3
		当サイトが使用しているアクセス解析ツールについて
	%p
		当サイトでは、Googleによるアクセス解析ツール「Googleアナリティクス」を利用しています。
		%br<>
		このGoogleアナリティクスはトラフィックデータの収集のためにCookieを使用しています。
		%br<>
		このトラフィックデータは匿名で収集されており、個人を特定するものではありません。
		%br<>
		この機能はCookieを無効にすることで収集を拒否することが出来ますので、お使いのブラウザの設定をご確認ください。
		%br<>
		この規約に関して、詳しくは
		= link_to %(こちら), %(http://www.google.com/analytics/terms/jp.html)
		、または
		= link_to %(こちら), %(https://www.google.com/intl/ja/policies/privacy/partners/)
		をクリックしてください。
		%br<>

	%dl
		%dt
			運営者
		%dd
			株式会社トヤソフト
		%dt
			EMAIL
		%dd
			info@toyasoft.com
		%dt
			初掲載
		%dd
			2017年10月8日

app/views/policies/terms/index.html.haml
-# app/views/policies/terms/index.html.haml
-# インターネットテレビくんについて

- set_meta_tags site: %(インターネットテレビくん), title: %(インターネットテレビくんについて), description: %(インターネットテレビくんご利用においてお読みください。), canonical: request.original_url

%section.about
	%h2
		インターネットテレビくんについて
	%p
		インターネットテレビくんとはTwitterタイムラインを利用した実験的インターネットテレビアプリケーションです。
		%br<>
		TwitterタイムラインAPIにより提供されたYoutube動画を24時間区切りでランキングしています。
		%br<>
    実験的アプリケーションですので、どなたでもご自由に無料でご覧いただけます。
    %br<>
    APIを提供してくださっているTwitter、勝手にフォローさせていただいている皆様に感謝します。
		%br<>
		公式ツイッターBotではトップツイートを随時更新ツイートしています。
		%br<>
		%br<>
		公式Twitter：
		= link_to %(@kanjizaitv), %(https://twitter.com/kanjizaitv), target: %(blank)
		%br<>
		%br<>
	%h3
		ご利用方法
	%p
		= link_to %(トップページ), root_path
		より現在のリアルタイムトレンドランキングをご覧いただけます。
		%br<>
		画像又は、タイトルをクリックするとYouTube動画をご視聴できます。
		%br<>
		%br<>
	%h3
		お問い合わせ
	%p
		ご意見、ご要望等は
		= link_to %(お問い合わせフォーム), new_contact_path
		よりお問い合わせください。